[manifest]
version = "1.0.0"
priority = -8 # Load slightly before smods fixes.toml

# Draw the ltd_button behind the Card
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = "if self.children.buy_and_use_button then"
position = "before"
payload = '''
if not SMODS.draw_ignore_keys and self.children.ltd_button then
    self.children.ltd_button:draw()
end
'''

# Prevent drawing the LTD button early
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = '''
if not v.custom_draw and k ~= 'focused_ui' and k ~= "front" and k ~= "back" and k ~= "soul_parts" and k ~= "center" and k ~= 'floating_sprite' and k~= "shadow" and k~= "use_button" and k ~= 'buy_button' and k ~= 'buy_and_use_button' and k~= "debuff" and k ~= 'price' and k~= 'particles' and k ~= 'h_popup' then v:draw() end
'''
position = "at"
payload = '''
if not SMODS.draw_ignore_keys and k == 'ltd_button' then
  goto __ltd_continue
end

if not v.custom_draw and k ~= 'focused_ui' and k ~= "front" and k ~= "back" and k ~= "soul_parts" and k ~= "center" and k ~= 'floating_sprite' and k~= "shadow" and k~= "use_button" and k ~= 'buy_button' and k ~= 'buy_and_use_button' and k~= "debuff" and k ~= 'price' and k~= 'particles' and k ~= 'h_popup' then v:draw() end

::__ltd_continue::
'''

# LTD mark
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = '''
card = self.config.card_key,
'''
position = "at"
payload = '''
card = self.config.card_key,
ltdm_saved_id = self.ltdm_state and self.ltdm_state.id,
'''

[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = "self.config.center_key = cardTable.save_fields.center"
position = "after"
payload = "self.ltdm_saved_id = cardTable.save_fields.ltdm_saved_id"


# Voucher support
[[patches]]
[patches.pattern]
target = "game.lua"
match_indent = true
pattern = "if G.GAME.current_round.voucher and G.P_CENTERS[G.GAME.current_round.voucher] then"
position = "at"
payload = '''
local ltdm_vouchers = LTDM.state.ltd:get_area_items('vouchers')
if ltdm_vouchers then
    for i, v in ipairs(ltdm_vouchers) do
        local _ltd_card = Card(
            G.shop_vouchers.T.x + G.shop_vouchers.T.w/2, G.shop_vouchers.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty,
            G.P_CENTERS[v.key], { bypass_discovery_center = true, bypass_discovery_ui = true, }
        )

        G.shop_vouchers.config.card_limit = i

        _ltd_card.ltdm_saved_id = v.id
        _ltd_card.shop_voucher = v.shop_voucher
        create_shop_card_ui(_ltd_card, 'Voucher', G.shop_vouchers)
        _ltd_card:start_materialize()
        G.shop_vouchers:emplace(_ltd_card)
    end
elseif G.GAME.current_round.voucher and G.P_CENTERS[G.GAME.current_round.voucher] then
'''

# SMODS v1.0.0~BETA-0301d-STEAMODDED and up
[[patches]]
[patches.pattern]
target = "game.lua"
match_indent = true
pattern = '''
local vouchers_to_spawn = 0
for _,_ in pairs(G.GAME.current_round.voucher.spawn) do vouchers_to_spawn = vouchers_to_spawn + 1 end
if vouchers_to_spawn < G.GAME.starting_params.vouchers_in_shop + (G.GAME.modifiers.extra_vouchers or 0) then
    SMODS.get_next_vouchers(G.GAME.current_round.voucher)
end
for _, key in ipairs(G.GAME.current_round.voucher or {}) do
    if G.P_CENTERS[key] and G.GAME.current_round.voucher.spawn[key] then
        SMODS.add_voucher_to_shop(key)
    end
end
'''
position = "at"
payload = '''
local ltdm_vouchers = LTDM.state.ltd:get_area_items('vouchers')
if ltdm_vouchers then
    G.GAME.current_round.voucher = { spawn = {} }
    for i, v in ipairs(ltdm_vouchers) do
        local _ltd_card = Card(
            G.shop_vouchers.T.x + G.shop_vouchers.T.w/2, G.shop_vouchers.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty,
            G.P_CENTERS[v.key], { bypass_discovery_center = true, bypass_discovery_ui = true, }
        )

        G.shop_vouchers.config.card_limit = i

        _ltd_card.ltdm_saved_id = v.id
        _ltd_card.shop_voucher = true
        create_shop_card_ui(_ltd_card, 'Voucher', G.shop_vouchers)
        _ltd_card:start_materialize()
        G.shop_vouchers:emplace(_ltd_card)
    end

    goto __ltd_voucher_continue
end

local vouchers_to_spawn = 0
for _,_ in pairs(G.GAME.current_round.voucher.spawn) do vouchers_to_spawn = vouchers_to_spawn + 1 end
if vouchers_to_spawn < G.GAME.starting_params.vouchers_in_shop + (G.GAME.modifiers.extra_vouchers or 0) then
    SMODS.get_next_vouchers(G.GAME.current_round.voucher)
end
for _, key in ipairs(G.GAME.current_round.voucher or {}) do
    if G.P_CENTERS[key] and G.GAME.current_round.voucher.spawn[key] then
        SMODS.add_voucher_to_shop(key)
    end
end

::__ltd_voucher_continue::
'''


# Fix Voucher LTD button drawing order
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
match_indent = true
pattern = '''{n=G.UIT.C, config={align = "cm", padding = 0.2, r=0.2, colour = G.C.BLACK, maxh = G.shop_vouchers.T.h+0.4}, nodes={'''
position = "at"
payload = '''
{n=G.UIT.C, config={align = "cm", padding = 0.2, r=0.2, colour = G.C.BLACK, maxh = G.shop_vouchers.T.h+0.4, draw_layer = 1}, nodes={
'''


# Booster pack
[[patches]]
[patches.pattern]
target = "game.lua"
match_indent = true
pattern = "if not G.GAME.current_round.used_packs[i] then"
position = "at"
payload = '''
local ltdm_booster_pack = LTDM.state.ltd:get_lock_item('booster')
if ltdm_booster_pack then
    G.GAME.current_round.used_packs[i] = ltdm_booster_pack.key
elseif not G.GAME.current_round.used_packs[i] then
'''

# Booster pack mark
[[patches]]
[patches.pattern]
target = "game.lua"
match_indent = true
pattern = "create_shop_card_ui(card, 'Booster', G.shop_booster)"
position = "before"
payload = '''
card.ltdm_saved_id = ltdm_booster_pack and ltdm_booster_pack.id
'''

# Discound voucher fix
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = '''
G.GAME.discount_percent = center_table.extra
for k, v in pairs(G.I.CARD) do
    if v.set_cost then v:set_cost() end
'''
position = "after"
payload = '''
if v.ltdm_state then
    LTDM.state.ltd:update_locked_item(v.ltdm_state.id, { key = 'price', val = v.cost })
end
'''


# Controller/Gamepad support
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
match_indent = true
pattern = '''
{n=G.UIT.C, config={align = "cm", func = 'show_infotip',object = Moveable(),ref_table = next(info_boxes) and info_boxes or nil}, nodes={
'''
position = "at"
payload = '''
{n=G.UIT.R, config={align = "cm", func = 'show_infotip',object = Moveable(),ref_table = next(info_boxes) and info_boxes or nil}, nodes={
'''
