[manifest]
version = "1.0.0"
priority = -8 # Load slightly before smods fixes.toml

# Draw the ltd_button behind the Card
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = "if self.children.buy_and_use_button then"
position = "before"
payload = '''
if self.children.ltd_button then
    self.children.ltd_button:draw()
end
'''

# Prevent drawing the
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = '''
if not v.custom_draw and k ~= 'focused_ui' and k ~= "front" and k ~= "back" and k ~= "soul_parts" and k ~= "center" and k ~= 'floating_sprite' and k~= "shadow" and k~= "use_button" and k ~= 'buy_button' and k ~= 'buy_and_use_button' and k~= "debuff" and k ~= 'price' and k~= 'particles' and k ~= 'h_popup' then v:draw() end
'''
position = "at"
payload = '''
if not v.custom_draw and k ~= 'focused_ui' and k ~= "front" and k ~= "back" and k ~= "soul_parts" and k ~= "center" and k ~= 'floating_sprite' and k~= "shadow" and k~= "use_button" and k ~= 'buy_button' and k ~= 'buy_and_use_button' and k ~= 'ltd_button' and k~= "debuff" and k ~= 'price' and k~= 'particles' and k ~= 'h_popup' then v:draw() end
'''
